-- Optional: load the current drops and reviews (run after schema.sql)
insert into public.drops (id,artist,tour_en,tour_zh,city,venue_en,venue_zh,date_label_en,date_label_zh,event_date,status,note_en,note_zh,image_url,published) values ('bigbang-sg-2026','BIGBANG','2026–2027 World Tour XX:COSMOS','2026–2027 世界巡回演唱会 XX:COSMOS','SG','Singapore National Stadium','新加坡国家体育场','Sat 17 Oct 2026 · 7pm','2026年10月17日（周六）· 晚上7点','2026-10-17','preorder','All categories except VIP Ultimate','除 VIP Ultimate 外所有票区','/assets/img/stage-beams.jpg',true) on conflict (id) do nothing;
insert into public.drops (id,artist,tour_en,tour_zh,city,venue_en,venue_zh,date_label_en,date_label_zh,event_date,status,note_en,note_zh,image_url,published) values ('tba-kl-1','[ARTIST]','[TOUR NAME]','[巡演名称]','KL','[VENUE]','[场馆]','[DD MMM 2026]','[2026年X月X日]',null,'soon','Get notified when sales open','开票时第一时间通知你','/assets/img/crowd-hands.jpg',true) on conflict (id) do nothing;
insert into public.drops (id,artist,tour_en,tour_zh,city,venue_en,venue_zh,date_label_en,date_label_zh,event_date,status,note_en,note_zh,image_url,published) values ('tba-sg-1','[ARTIST]','[TOUR NAME]','[巡演名称]','SG','[VENUE]','[场馆]','[DD MMM 2026]','[2026年X月X日]',null,'soon','Get notified when sales open','开票时第一时间通知你','/assets/img/festival-night.jpg',true) on conflict (id) do nothing;
insert into public.reviews (id,handle,text,tags,event,source,screenshot_url,visible,sort_order) values ('r1','aria.abjalil','Totally legit — got the e-ticket for sure. I was kinda nervous at first, but the seller walked me through everything. Luckily I managed to snag the ticket, even if it was a bit last minute.',array['Great communication','Knows their stuff']::text[],'HIGHLIGHT Live, Malaysia','Carousell','/assets/img/reviews/review-1.jpg',true,1) on conflict (id) do nothing;
insert into public.reviews (id,handle,text,tags,event,source,screenshot_url,visible,sort_order) values ('r2','westasiesta','Trusted seller! Replied to my queries about the tickets very quickly, and was able to deal in person. Trustworthy, even secured me a poster! Polite and helpful seller. Thank you, I had a great time!',array['Value for money','Great communication']::text[],'MONSTA X, Malaysia','Carousell','/assets/img/reviews/review-2.jpg',true,2) on conflict (id) do nothing;
insert into public.reviews (id,handle,text,tags,event,source,screenshot_url,visible,sort_order) values ('r3','hoodawon','Nice service from the seller! Fast replies and very trustworthy. It was a last-minute purchase, and thankfully they managed to get the best seats for me and my sister.',array['Value for money','Great communication']::text[],'MONSTA X, Malaysia','Carousell','/assets/img/reviews/review-4.jpg',true,3) on conflict (id) do nothing;
insert into public.reviews (id,handle,text,tags,event,source,screenshot_url,visible,sort_order) values ('r4','bluelikeocean','Seller was so patient and was willing to wait for me to make payment. Great seller to deal with and even gave me a good price for my seat. Hope to deal with you again. Thank you!',array['Great communication','Above and beyond']::text[],'MONSTA X, Malaysia','Carousell','/assets/img/reviews/review-5.jpg',true,4) on conflict (id) do nothing;
insert into public.reviews (id,handle,text,tags,event,source,screenshot_url,visible,sort_order) values ('r5','kimja999','Not regret buying this from this seller. Really trustworthy!',array['Great communication','Unique listings']::text[],'MONSTA X, Malaysia','Carousell','/assets/img/reviews/review-3.jpg',true,5) on conflict (id) do nothing;
insert into public.faqs (id,q_en,q_zh,a_en,a_zh,visible,sort_order) values ('faq-1','How much is your fee?','服务费是多少？','A per-ticket service fee on top of the face value. You get the full breakdown in writing before you pay.','在票面价之外按每张票收取服务费。付款前会提供书面明细。',true,1) on conflict (id) do nothing;
insert into public.faqs (id,q_en,q_zh,a_en,a_zh,visible,sort_order) values ('faq-2','When do I pay?','什么时候付款？','Full payment upfront. You receive an Order ID and receipt straight away.','需预先全额付款，付款后立即获得订单编号与收据。',true,2) on conflict (id) do nothing;
insert into public.faqs (id,q_en,q_zh,a_en,a_zh,visible,sort_order) values ('faq-3','What if you can’t secure my tickets?','如果没抢到票怎么办？','If the quota is hit or your order isn’t secured, you get a full refund within 3 working days.','若名额已满或未能抢到，将于 3 个工作日内全额退款。',true,3) on conflict (id) do nothing;
insert into public.faqs (id,q_en,q_zh,a_en,a_zh,visible,sort_order) values ('faq-4','Are the tickets physical or e-tickets?','是实体票还是电子票？','Most of the time they’re e-tickets, transferred through the organiser’s official platform — unless the listing specifically says physical ticket.','大多数情况下是电子票，通过主办方官方平台转票——除非商品信息特别注明为实体票。',true,4) on conflict (id) do nothing;
insert into public.faqs (id,q_en,q_zh,a_en,a_zh,visible,sort_order) values ('faq-5','Can we sit together?','可以坐在一起吗？','Yes — side-by-side seats are available from 2 tickets. Final seats are assigned by the organiser; we’ll note your preferred zone.','可以——2 张起可安排连座。最终座位由主办方分配，我们会备注你偏好的区域。',true,5) on conflict (id) do nothing;
insert into public.faqs (id,q_en,q_zh,a_en,a_zh,visible,sort_order) values ('faq-6','What about name-bound or ID-checked tickets?','实名制或需核对证件的门票怎么办？','Some events require the ticket name to match your ID. For those, Buy For You purchases in your name where the organiser allows it. We’ll tell you the rules for each event before you pay.','部分演出要求票上姓名与证件一致。遇到这类演出，我们会在主办方允许的情况下以你的名义代抢。每场演出的规则都会在付款前说明。',true,6) on conflict (id) do nothing;
insert into public.settings (key, value) values ('contacts', '{"whatsapp_number": "+60 12-659 2025", "whatsapp_link": "https://wa.me/message/254MFSUP73ZGN1", "whatsapp_on": true, "instagram_url": "https://www.instagram.com/authentix_my", "instagram_handle": "authentix_my", "instagram_on": true, "carousell_url": "http://carousell.app.link/lHrZAsmCeKb", "carousell_on": true}'::jsonb) on conflict (key) do nothing;
